const failFunction = () => {
  return 42;
};

failFunction();
